[libdefaults]
  default_realm = COAMO.COM.BR
  dns_lookup_realm = true
  dns_lookup_kdc = true
  rdns = false
  ticket_lifetime = 10h
  renew_lifetime = 7d
  forwardable = true

[realms]
  COAMO.COM.BR = {
    kdc = admdc01.coamo.com.br
    kdc = admdc02.coamo.com.br
    kdc = admdc03.coamo.com.br
    kdc = admdc04.coamo.com.br
    admin_server = admdc01.coamo.com.br
  }

[domain_realm]
  .coamo.com.br = COAMO.COM.BR
  coamo.com.br = COAMO.COM.BR
